In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('anime.csv')

In [3]:
df

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [4]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [5]:
df.iloc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [6]:
def extract_episode(txt):
    check = False
    data = ""

    for i in txt:
        if i == '(':
            check = True
            continue   # '(' ko add nahi karna

        if i == ')':
            check = False
            break      # ')' pe stop karna

        if check:
            data = data + i

    return data

def name(txt):
    
    data = ""

    for i in txt:
        if i == '(':
            break

        else: data=data+i

    return data

In [7]:
df['episode']=df['Title'].apply(extract_episode).str.split(' ').str[0]
df['Name']=df['Title'].apply(name).str.split(':').str[0]

In [8]:
df

,Rank,Title,Score,episode,Name
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Fullmetal Alchemist
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Steins;GateTV
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Bleach
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Gintama°TV
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Shingeki no Kyojin Season 3 Part 2TV
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Gintama'TV
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Gintama
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Hunter x Hunter TV
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Kaguya-sama wa Kokurasetai
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Gintama'
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Shingeki no Kyojin
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Ginga Eiyuu DensetsuOVA
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Bleach
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Fruits Basket
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Gintama.TV
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,GintamaTV
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Koe no KatachiMovie
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,3-gatsu no Lion 2nd SeasonTV
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Clannad
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Code Geass
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Gintama Movie 2
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Violet Evergarden MovieMovie
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Owarimonogatari 2nd SeasonTV
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Gintama.
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,MonsterTV
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Kimi no Na wa.Movie
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Kaguya-sama wa Kokurasetai
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Bocchi the Rock!TV
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,The First Slam DunkMovie
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Vinland Saga Season 2TV
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jujutsu Kaisen 2nd SeasonTV
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Gintama.
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Kingdom 3rd SeasonTV
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Mob Psycho 100 IITV
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Shingeki no Kyojin
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Kimetsu no Yaiba
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Kizumonogatari III
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,"""Oshi no Ko""TV"
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Sen to Chihiro no KamikakushiMovie
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Monogatari Series
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Shingeki no Kyojin
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Hajime no IppoTV
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Cowboy BebopTV
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Kingdom 4th SeasonTV
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Vinland SagaTV
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Mushishi Zoku Shou 2nd SeasonTV
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Shouwa Genroku Rakugo Shinjuu
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Mob Psycho 100 IIITV
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Rurouni Kenshin

In [9]:
#df.drop('Title',axis=1,inplace=True)

In [10]:
df

,Rank,Title,Score,episode,Name
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Fullmetal Alchemist
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Steins;GateTV
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Bleach
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Gintama°TV
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Shingeki no Kyojin Season 3 Part 2TV
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Gintama'TV
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Gintama
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Hunter x Hunter TV
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Kaguya-sama wa Kokurasetai
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Gintama'
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Shingeki no Kyojin
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Ginga Eiyuu DensetsuOVA
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Bleach
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Fruits Basket
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Gintama.TV
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,GintamaTV
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Koe no KatachiMovie
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,3-gatsu no Lion 2nd SeasonTV
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Clannad
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Code Geass
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Gintama Movie 2
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Violet Evergarden MovieMovie
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Owarimonogatari 2nd SeasonTV
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Gintama.
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,MonsterTV
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Kimi no Na wa.Movie
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Kaguya-sama wa Kokurasetai
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Bocchi the Rock!TV
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,The First Slam DunkMovie
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Vinland Saga Season 2TV
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jujutsu Kaisen 2nd SeasonTV
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Gintama.
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Kingdom 3rd SeasonTV
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Mob Psycho 100 IITV
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Shingeki no Kyojin
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Kimetsu no Yaiba
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Kizumonogatari III
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,"""Oshi no Ko""TV"
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Sen to Chihiro no KamikakushiMovie
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Monogatari Series
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Shingeki no Kyojin
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Hajime no IppoTV
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Cowboy BebopTV
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Kingdom 4th SeasonTV
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Vinland SagaTV
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Mushishi Zoku Shou 2nd SeasonTV
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Shouwa Genroku Rakugo Shinjuu
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Mob Psycho 100 IIITV
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Rurouni Kenshin

In [11]:
df['episode'] = df['episode'].astype(int)

In [14]:
type(df.loc[2]['episode'])

numpy.int32

In [17]:
df['timespan']=df['Title'].str.split(')').str[1].str.split(',').str[0]

In [18]:
df

,Rank,Title,Score,episode,Name,timespan
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Fullmetal Alchemist,Apr 2009 - Jul 20103
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Steins;GateTV,Apr 2011 - Sep 20112
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Bleach,Oct 2022 - Dec 2022474
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Gintama°TV,Apr 2015 - Mar 2016605
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Shingeki no Kyojin Season 3 Part 2TV,Apr 2019 - Jul 20192
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Gintama'TV,Apr 2011 - Mar 2012534
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Gintama,Jan 2021 - Jan 2021137
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Hunter x Hunter TV,Oct 2011 - Sep 20142
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Kaguya-sama wa Kokurasetai,Apr 2022 - Jun 2022851
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Gintama',Oct 2012 - Mar 2013313
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Shingeki no Kyojin,Mar 2023 - May 2023472
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Ginga Eiyuu DensetsuOVA,Jan 1988 - Mar 1997309
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Bleach,Jul 2023 - Aug 2023 178
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Fruits Basket,Apr 2021 - Jun 2021443
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Gintama.TV,Jan 2017 - Mar 2017302
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,GintamaTV,Apr 2006 - Mar 20101
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Koe no KatachiMovie,Sep 2016 - Sep 20162
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,3-gatsu no Lion 2nd SeasonTV,Oct 2017 - Mar 2018388
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Clannad,Oct 2008 - Mar 20091
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Code Geass,Apr 2008 - Sep 20081
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Gintama Movie 2,Jul 2013 - Jul 2013232
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Violet Evergarden MovieMovie,Sep 2020 - Sep 2020564
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Owarimonogatari 2nd SeasonTV,Aug 2017 - Aug 2017385
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Gintama.,Jul 2018 - Oct 2018189
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,MonsterTV,Apr 2004 - Sep 20051
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Kimi no Na wa.Movie,Aug 2016 - Aug 20162
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Kaguya-sama wa Kokurasetai,Dec 2022 - Dec 2022205
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Bocchi the Rock!TV,Oct 2022 - Dec 2022464
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,The First Slam DunkMovie,Dec 2022 - Dec 202227
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Vinland Saga Season 2TV,Jan 2023 - Jun 2023495
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jujutsu Kaisen 2nd SeasonTV,Jul 2023 - Aug 2023 556
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Gintama.,Jan 2018 - Mar 2018203
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Kingdom 3rd SeasonTV,Apr 2020 - Oct 202193
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Mob Psycho 100 IITV,Jan 2019 - Apr 20191
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Shingeki no Kyojin,Dec 2020 - Mar 20211
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Kimetsu no Yaiba,Dec 2021 - Feb 20221
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Kizumonogatari III,Jan 2017 - Jan 2017445
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,"""Oshi no Ko""TV",Apr 2023 - Jun 2023645
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,Oct 2016 - Dec 20161
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Sen to Chihiro no KamikakushiMovie,Jul 2001 - Jul 20011
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Monogatari Series,Jul 2013 - Dec 2013653
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Shingeki no Kyojin,Jan 2022 - Apr 20221
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Hajime no IppoTV,Oct 2000 - Mar 2002558
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Cowboy BebopTV,Apr 1998 - Apr 19991
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Kingdom 4th SeasonTV,Apr 2022 - Oct 202255
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Vinland SagaTV,Jul 2019 - Dec 20191
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Mushishi Zoku Shou 2nd SeasonTV,Oct 2014 - Dec 2014257
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Shouwa Genroku Rakugo Shinjuu,Jan 2017 - Mar 2017182
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Mob Psycho 100 IIITV,Oct 2022 - Dec 2022600
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Rurouni Kenshin,Feb 1999 - Sep 1999271